### PR TITLE
[HxSearchBox] TextQuery item can be selected even when AllowTextQuery=false

### PR DESCRIPTION
**Pull request by Harvey1214**

### CODE REVIEW

**Comment by Harvey1214** [comment]
@crdo @hakenr another question is whether we want to disallow selecting the input with the arrow keys when `AllowTextQuery=false` as it doesn't carry any purpose I believe (same thing for `HxAutosuggest`). Please let me know what you think, thanks.

**Review by hakenr — CHANGES_REQUESTED** [review]
@Harvey1214 Same issue applies in the opposite direction - the start (for those scenarios, where we apply the "hightlight first suggestion" approach). We should keep the first item selected (should not "select the input"), when the `AllowTextQuery` is `false`.

**Review by hakenr — CHANGES_REQUESTED** [review]
Both `HxAutosuggest` and `HxSearchBox` (SuggestionsOnly-mode) allow me to navigate "up" from the first item and get to the "nothing selected" state.
...which si something we are trying to solve, isn't it?

**Review by hakenr — APPROVED** [review]
lgtm

**Pull request merged**
