### PR TITLE
Attribute splatting for HxContextMenu dropdown trigger element

### PR DESCRIPTION
**Pull request by crdo**
Adressing Issue #118 [HxGrid] Context menu causes scrollbar

### CODE REVIEW

**Review by hakenr — COMMENTED** [review]
Although I understand the current need (#118), I'm not satisfied with the selective decision we are making here when splatting the additional attributes to *some* inner `.hx-context-menu-btn` element (`div.hx-context-menu > div.dropdown > div.hx-context-menu-btn`).

In the case of `HxInputBase` components, the additional attributes are splatted to the `input` (to maintain the `InputBase` approach). All the other components (hopefully) are splatting the additional attributes to the dominant element (the outermost one).

We should find another way to achieve the goal. Is there any relevant scenario where the `data-bs-popper-config='{"strategy":"fixed"}'` should not be used? Can we set this config always?

**Comment by crdo** [comment]
I don't think it is a good idea to make `"strategy":"fixed"` default. If the `.dropdown-menu` element is set as `position: fixed;` its position is calculated and updated when you scroll the window. While with `position: absolute;`, it is calculated on the first render and thats it.

**Comment by crdo** [comment]
On the other hand - if you start scrolling while the `HxContextMenu` is open, it disappears as you no longer hover the row.

**Comment by hakenr** [comment]
New `PopperStrategy="[Absolute|Fixed]"` parameter?

**Comment by crdo** [comment]
Either PopperStrategy or PositionStrategy works for me.

**Comment by hakenr** [comment]
Added new `PopperStrategy` parameter to `HxContextMenu`, which allows to fix the issue:
```razor
  <HxContextMenu PopperStrategy="PopperStrategy.Fixed">
```
If you feel this should be configurable as application-wide default with `HxContextMenu.Defaults.PopperStrategy`, please create a separate issue.

**Pull request merged**
