### PR TITLE
Fixes [HxSearchBox] Top dropdown position not attached to input #618

### LINKED ISSUE #618: [HxSearchBox] Top dropdown position not attached to input
image

cc @crdo

### PR DESCRIPTION
**Pull request by crdo**
Fixes #618

### CODE REVIEW

**Review by hakenr — COMMENTED** [review]
@crdo Just moving the `label` above the `HxDropdown` + dropped the `DropdownReference`, or did I miss something?

**Comment by crdo** [comment]
Yes, but still buggy. If you use a start template with a button, it triggers the search dropdown. It should be overhauled to the same structure as is on the `HxAutosuggest`.

**Comment by hakenr** [comment]
@crdo Should I merge this PR?

**Comment by crdo** [comment]
@hakenr it can be merged. The other bug with clicking on addons causing the search dropdown to open will be handled in separate issue.

**Pull request merged**
