### PR TITLE
[HxMultiSelect] Set cursor on hover to default instead of text #154

### PR DESCRIPTION
**Pull request by Harvey1214**
@hakenr Do you think this is a viable solution? It achieves pointer cursor on hover but also centers the text, however that can be easily adjusted if need be.

### CODE REVIEW

**Review by hakenr — COMMENTED** [review]
@crdo Can you please review? Not sure the `<input type="button">` is an ideal approach for cursor shape here.

**Comment by crdo** [comment]
From the accessibility POV not. I'd go for rule in css isolation.

**Review by hakenr — CHANGES_REQUESTED** [review]
@Harvey1214 Please revert and set the cursor shape with appropriate CSS rule (CSS isolation).

**Comment by Harvey1214** [comment]
@hakenr completed

**Pull request merged**
